// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxkecssnvkchmotmzcns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4a2Vjc3NudmtjaG1vdG16Y25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDM0NDksImV4cCI6MjA3MTU3OTQ0OX0.fnkbSsJbRdAv3UeMMf1synRis-o33ejW9GooGUSwpDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});